trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
  projects: |
    StripeIntegration.Shared/StripeIntegration.Shared.csproj
    StripeIntegration.ViewModels/StripeIntegration.ViewModels.csproj
    Client/StripeIntegration.Services/StripeIntegration.Services.csproj
    Client/StripeIntegration.Components/StripeIntegration.Components.csproj
    Client/StripeIntegration.Website/StripeIntegration.Website.csproj

steps:

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      includePreviewVersions: true

  - task: NuGetCommand@2
    displayName: 'Remove nuget.org Source'
    inputs:
      command: 'custom'
      arguments: 'source Remove -Name nuget.org'

  - task: NuGetCommand@2
    displayName: 'Add BlazorComponentHeap NuGet Source'
    inputs:
      command: 'custom'
      arguments: 'source Add -Name BlazorComponentHeap -Source $(bchSource) -UserName $(System.AccessToken) -Password $(System.AccessToken)'

#  - task: NuGetCommand@2
#    displayName: 'Add nuget.org Source'
#    inputs:
#      command: 'custom'
#      arguments: 'source Add -Name nuget.org -Source https://api.nuget.org/v3/index.json'

  - task: NuGetAuthenticate@1

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: $(projects)

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: --configuration $(buildConfiguration)
      projects: $(projects)

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: $(projects)
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false

  - script: |
      find $(build.ArtifactStagingDirectory) -type f
    displayName: 'Print Build.ArtifactStagingDirectory'

  - task: CopyFilesOverSSH@0
    displayName: 'Deploy to Droplet'
    inputs:
      sshEndpoint: $(connectionToDroplet)
      sourceFolder: '$(build.ArtifactStagingDirectory)'
      contents: '**'
      targetFolder: '/var/www/$(appPath)'
      cleanTargetFolder: true